# Generated by Django 5.1.7 on 2025-06-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('NE', 'Necklace'), ('RI', 'Ring'), ('WA', 'Watch'), ('BR', 'Bracelate'), ('LO', 'Locket'), ('EA', 'Earings')], max_length=2),
        ),
    ]
